# Generated by Django 5.0.6 on 2024-06-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_author_bio_remove_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
    ]
